name: Build and Deploy (nickhatboecker)

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        outputs:
            DIST_PATH: ${{ steps.build-output.outputs.DIST_PATH }}

        env:
            # Create these in repository under Settings > Secrets and variables > Actions
            VUE_APP_APPWRITE_ENDPOINT: ${{ vars.VUE_APP_APPWRITE_ENDPOINT }}
            VUE_APP_APPWRITE_PROFILE: 'nickhatboecker'
            VUE_APP_PLAUSIBLE_DOMAIN: 'nickhatboecker.de'

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21'

            - name: Install dependencies
              run: yarn install

            - name: Build project
              run: yarn build

            - name: Verify build output
              run: ls -alh dist

            - name: Upload files for deployment
              uses: actions/upload-artifact@v4
              with:
                  name: dist_path
                  path: dist
    deploy:
        needs: build
        runs-on: ubuntu-latest

        env:
            # Create this in repository under Settings > Secrets and variables > Actions
            SERVER_IP: ${{ secrets.SERVER_IP }}
            SSH_PORT: ${{ secrets.SSH_PORT }}

            # Create an SSH key and put the private key in repository under Settings > Secrets and variables > Actions
            # Put the public key in ~/.ssh/authorized_keys on deploy server.
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            SSH_USER: ${{ secrets.SSH_USER }}
            DIST_PATH: ${{ needs.build.outputs.DIST_PATH }}

        steps:
            - name: Download files
              uses: actions/download-artifact@v4
              with:
                  name: dist_path
            - name: Deploy to server
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  rsync --prune-empty-dirs -ahz -e "ssh -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no" ./ ${{ env.SSH_USER }}@${{ env.SERVER_IP }}:/var/www/the5kyliner.de/linktree
